/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.205.0Release
// Tag = production/release/21.205.0-0-gb3c261eb
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit

/**
 * Reads FIT files.
 *
 * ```kotlin
 * val result = FitDecoder(bytes).decode()
 * result.errors.forEach { println(it) }
 * result.messages.recordMesgs.forEach { println(it.heartRate) }
 * ```
 *
 * [decode] never throws on malformed input: it returns everything that decoded
 * before the problem alongside a description of it, because a truncated file
 * usually still holds most of an activity. The streaming entry points do throw,
 * since they have no result object to carry the error in.
 */
public class FitDecoder(
    private val bytes: ByteArray,
) {
    /** True when the input opens with a plausible FIT header. */
    public fun isFit(): Boolean = isFit(bytes)

    /** True when every chained file's header CRC and file CRC check out. */
    public fun checkIntegrity(): Boolean {
        if (!isFit()) return false
        return try {
            val cursor = MesgCursor(ByteReader(bytes), DecodeOptions(mode = DecodeMode.NORMAL))
            while (cursor.hasNext()) cursor.next()
            true
        } catch (_: FitException) {
            false
        }
    }

    /**
     * Decodes the whole input.
     *
     * Never throws: problems come back in [DecodeResult.errors].
     */
    public fun decode(options: DecodeOptions = DecodeOptions()): DecodeResult {
        val messages = FitMessages()
        val ordered = mutableListOf<Mesg>()
        val errors = mutableListOf<FitError>()
        var profileVersion: UShort? = null

        val cursor = MesgCursor(ByteReader(bytes), options)
        try {
            while (cursor.hasNext()) {
                val mesg = cursor.next()
                ordered.add(mesg)
                messages.add(mesg)
            }
        } catch (e: FitFormatException) {
            errors.add(FitError(e))
        } catch (e: FitException) {
            errors.add(FitError(e.message ?: "decode error", -1, e))
        } finally {
            profileVersion = cursor.profileVersion
            messages.developerFieldDescriptions.addAll(cursor.developerData.fieldDescriptions)
        }

        if (options.mergeHeartRates && options.expandComponents) {
            HrMesgUtil.mergeHeartRates(messages.hrMesgs, messages.recordMesgs)
        }

        return DecodeResult(messages, ordered, profileVersion, errors)
    }

    /**
     * Decodes lazily, handing each message to [onMesg] as it is read.
     *
     * Nothing is retained, so this is the entry point for files too large to
     * hold decoded in memory. Returns the errors that stopped the decode, if any.
     */
    public fun read(options: DecodeOptions = DecodeOptions(), onMesg: (Mesg) -> Unit): List<FitError> {
        val errors = mutableListOf<FitError>()
        try {
            for (mesg in asSequence(options)) onMesg(mesg)
        } catch (e: FitFormatException) {
            errors.add(FitError(e))
        }
        return errors
    }

    /**
     * The file's messages as a lazily decoded [Sequence].
     *
     * Throws [FitFormatException] mid-iteration on malformed input. Note that
     * [DecodeOptions.mergeHeartRates] cannot apply here: merging needs the whole
     * file, which is exactly what streaming avoids holding.
     */
    public fun asSequence(options: DecodeOptions = DecodeOptions()): Sequence<Mesg> =
        Sequence { MesgCursor(ByteReader(bytes), options) }

    public companion object {
        /** True when [bytes] opens with a plausible FIT header. */
        public fun isFit(bytes: ByteArray): Boolean {
            if (bytes.size < Fit.HEADER_WITHOUT_CRC_SIZE) return false
            return try {
                val header = FileHeader.read(ByteReader(bytes))
                header.isValid && bytes.size >= header.headerSize + header.dataSize.toInt()
            } catch (_: FitException) {
                false
            }
        }
    }
}
