/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit

import com.garmin.fit.types.*
import kotlin.time.Instant

/**
 * The FIT `split_summary` message.
 *
 * A thin typed view over [Mesg]: the accessors below read and write the same
 * numbered fields the untyped API exposes, so nothing is hidden by using them.
 */
public open class SplitSummaryMesg : Mesg {
    public constructor() : super("SplitSummary", Profile.MesgNum.SPLIT_SUMMARY)

    public constructor(mesg: Mesg) : super(mesg)

    internal constructor(mesg: Mesg, adopt: Boolean) : super(mesg, adopt)

    /** message_index. */
    public var messageIndex: UShort?
        get() = getFieldValue(MESSAGE_INDEX_FIELD_NUM) as? UShort
        set(value) = setFieldValue(MESSAGE_INDEX_FIELD_NUM, value)

    /** split_type. */
    public var splitType: SplitType?
        get() = (getFieldValue(SPLIT_TYPE_FIELD_NUM) as? UByte)?.let { SplitType.fromValue(it) }
        set(value) = setFieldValue(SPLIT_TYPE_FIELD_NUM, value?.value)

    /** num_splits. */
    public var numSplits: UShort?
        get() = getFieldValue(NUM_SPLITS_FIELD_NUM) as? UShort
        set(value) = setFieldValue(NUM_SPLITS_FIELD_NUM, value)

    /** total_timer_time, in s. */
    public var totalTimerTime: Double?
        get() = getFieldValue(TOTAL_TIMER_TIME_FIELD_NUM) as? Double
        set(value) = setFieldValue(TOTAL_TIMER_TIME_FIELD_NUM, value)

    /** total_distance, in m. */
    public var totalDistance: Double?
        get() = getFieldValue(TOTAL_DISTANCE_FIELD_NUM) as? Double
        set(value) = setFieldValue(TOTAL_DISTANCE_FIELD_NUM, value)

    /** avg_speed, in m/s. */
    public var avgSpeed: Double?
        get() = getFieldValue(AVG_SPEED_FIELD_NUM) as? Double
        set(value) = setFieldValue(AVG_SPEED_FIELD_NUM, value)

    /** max_speed, in m/s. */
    public var maxSpeed: Double?
        get() = getFieldValue(MAX_SPEED_FIELD_NUM) as? Double
        set(value) = setFieldValue(MAX_SPEED_FIELD_NUM, value)

    /** total_ascent, in m. */
    public var totalAscent: UShort?
        get() = getFieldValue(TOTAL_ASCENT_FIELD_NUM) as? UShort
        set(value) = setFieldValue(TOTAL_ASCENT_FIELD_NUM, value)

    /** total_descent, in m. */
    public var totalDescent: UShort?
        get() = getFieldValue(TOTAL_DESCENT_FIELD_NUM) as? UShort
        set(value) = setFieldValue(TOTAL_DESCENT_FIELD_NUM, value)

    /** avg_heart_rate, in bpm. */
    public var avgHeartRate: UByte?
        get() = getFieldValue(AVG_HEART_RATE_FIELD_NUM) as? UByte
        set(value) = setFieldValue(AVG_HEART_RATE_FIELD_NUM, value)

    /** max_heart_rate, in bpm. */
    public var maxHeartRate: UByte?
        get() = getFieldValue(MAX_HEART_RATE_FIELD_NUM) as? UByte
        set(value) = setFieldValue(MAX_HEART_RATE_FIELD_NUM, value)

    /** avg_vert_speed, in m/s. */
    public var avgVertSpeed: Double?
        get() = getFieldValue(AVG_VERT_SPEED_FIELD_NUM) as? Double
        set(value) = setFieldValue(AVG_VERT_SPEED_FIELD_NUM, value)

    /** total_calories, in kcal. */
    public var totalCalories: UInt?
        get() = getFieldValue(TOTAL_CALORIES_FIELD_NUM) as? UInt
        set(value) = setFieldValue(TOTAL_CALORIES_FIELD_NUM, value)

    /** active_time, in s. total active time in all split rounds */
    public var activeTime: Double?
        get() = getFieldValue(ACTIVE_TIME_FIELD_NUM) as? Double
        set(value) = setFieldValue(ACTIVE_TIME_FIELD_NUM, value)

    /** total_moving_time, in s. */
    public var totalMovingTime: Double?
        get() = getFieldValue(TOTAL_MOVING_TIME_FIELD_NUM) as? Double
        set(value) = setFieldValue(TOTAL_MOVING_TIME_FIELD_NUM, value)

    public companion object {
        public const val MESSAGE_INDEX_FIELD_NUM: UByte = 254u
        public const val SPLIT_TYPE_FIELD_NUM: UByte = 0u
        public const val NUM_SPLITS_FIELD_NUM: UByte = 3u
        public const val TOTAL_TIMER_TIME_FIELD_NUM: UByte = 4u
        public const val TOTAL_DISTANCE_FIELD_NUM: UByte = 5u
        public const val AVG_SPEED_FIELD_NUM: UByte = 6u
        public const val MAX_SPEED_FIELD_NUM: UByte = 7u
        public const val TOTAL_ASCENT_FIELD_NUM: UByte = 8u
        public const val TOTAL_DESCENT_FIELD_NUM: UByte = 9u
        public const val AVG_HEART_RATE_FIELD_NUM: UByte = 10u
        public const val MAX_HEART_RATE_FIELD_NUM: UByte = 11u
        public const val AVG_VERT_SPEED_FIELD_NUM: UByte = 12u
        public const val TOTAL_CALORIES_FIELD_NUM: UByte = 13u
        public const val ACTIVE_TIME_FIELD_NUM: UByte = 65u
        public const val TOTAL_MOVING_TIME_FIELD_NUM: UByte = 77u

        /**
         * The profile definition of every field of this message, with no values.
         *
         * Built once when this class is first touched, and handed out only as
         * copies, so the decoder pays for a message type it never meets nothing.
         */
        internal val PROTOTYPE_FIELDS: Map<Int, Field> = buildPrototypeFields()

        private fun buildPrototypeFields(): Map<Int, Field> {
            val fields = LinkedHashMap<Int, Field>()
            fields[254] = Field("MessageIndex", 254u, BaseType.UINT16, 1.0, 0.0, "", false)
            fields[0] = Field("SplitType", 0u, BaseType.ENUM, 1.0, 0.0, "", false)
            fields[3] = Field("NumSplits", 3u, BaseType.UINT16, 1.0, 0.0, "", false)
            fields[4] = Field("TotalTimerTime", 4u, BaseType.UINT32, 1000.0, 0.0, "s", false)
            fields[5] = Field("TotalDistance", 5u, BaseType.UINT32, 100.0, 0.0, "m", false)
            fields[6] = Field("AvgSpeed", 6u, BaseType.UINT32, 1000.0, 0.0, "m/s", false)
            fields[7] = Field("MaxSpeed", 7u, BaseType.UINT32, 1000.0, 0.0, "m/s", false)
            fields[8] = Field("TotalAscent", 8u, BaseType.UINT16, 1.0, 0.0, "m", false)
            fields[9] = Field("TotalDescent", 9u, BaseType.UINT16, 1.0, 0.0, "m", false)
            fields[10] = Field("AvgHeartRate", 10u, BaseType.UINT8, 1.0, 0.0, "bpm", false)
            fields[11] = Field("MaxHeartRate", 11u, BaseType.UINT8, 1.0, 0.0, "bpm", false)
            fields[12] = Field("AvgVertSpeed", 12u, BaseType.SINT32, 1000.0, 0.0, "m/s", false)
            fields[13] = Field("TotalCalories", 13u, BaseType.UINT32, 1.0, 0.0, "kcal", false)
            fields[65] = Field("ActiveTime", 65u, BaseType.UINT32, 1000.0, 0.0, "s", false)
            fields[77] = Field("TotalMovingTime", 77u, BaseType.UINT32, 1000.0, 0.0, "s", false)
            return fields
        }
    }
}
