/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * Named values for the FIT profile type `attitude_validity`.
 *
 * This type is not modelled as an enum: it is a bit mask or a scalar with named
 * thresholds, so values outside the list below are meaningful.
 */
public object AttitudeValidityValues {
    public const val TRACK_ANGLE_HEADING_VALID: UShort = 0x0001u
    public const val PITCH_VALID: UShort = 0x0002u
    public const val ROLL_VALID: UShort = 0x0004u
    public const val LATERAL_BODY_ACCEL_VALID: UShort = 0x0008u
    public const val NORMAL_BODY_ACCEL_VALID: UShort = 0x0010u
    public const val TURN_RATE_VALID: UShort = 0x0020u
    public const val HW_FAIL: UShort = 0x0040u
    public const val MAG_INVALID: UShort = 0x0080u
    public const val NO_GPS: UShort = 0x0100u
    public const val GPS_INVALID: UShort = 0x0200u
    public const val SOLUTION_COASTING: UShort = 0x0400u
    public const val TRUE_TRACK_ANGLE: UShort = 0x0800u
    public const val MAGNETIC_HEADING: UShort = 0x1000u

    /** The FIT invalid sentinel for this type's base type. */
    public val INVALID: UShort = UShort.MAX_VALUE
}
