/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.213.0Release
// Tag = production/release/21.213.0-0-g9e10ea9c
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `autolap_trigger`.
 */
public enum class AutolapTrigger(
    public val value: UByte,
) {
    TIME(0u),
    DISTANCE(1u),
    POSITION_START(2u),
    POSITION_LAP(3u),
    POSITION_WAYPOINT(4u),
    POSITION_MARKED(5u),
    OFF(6u),
    AUTO_SELECT(13u),

    /** Returned for any raw value not present in the profile. */
    INVALID(UByte.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UByte, AutolapTrigger> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UByte): AutolapTrigger =
            byValue[value] ?: INVALID
    }
}
