/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.205.0Release
// Tag = production/release/21.205.0-0-gb3c261eb
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * Named values for the FIT profile type `auto_activity_detect`.
 *
 * This type is not modelled as an enum: it is a bit mask or a scalar with named
 * thresholds, so values outside the list below are meaningful.
 */
public object AutoActivityDetectValues {
    public const val NONE: UInt = 0x00000000u
    public const val RUNNING: UInt = 0x00000001u
    public const val CYCLING: UInt = 0x00000002u
    public const val SWIMMING: UInt = 0x00000004u
    public const val WALKING: UInt = 0x00000008u
    public const val ELLIPTICAL: UInt = 0x00000020u
    public const val SEDENTARY: UInt = 0x00000400u

    /** The FIT invalid sentinel for this type's base type. */
    public val INVALID: UInt = UInt.MAX_VALUE
}
