/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.205.0Release
// Tag = production/release/21.205.0-0-gb3c261eb
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * Named values for the FIT profile type `backlight_timeout`.
 *
 * Timeout in seconds.
 *
 * This type is not modelled as an enum: it is a bit mask or a scalar with named
 * thresholds, so values outside the list below are meaningful.
 */
public object BacklightTimeoutValues {
    public const val INFINITE: UByte = 0u // Backlight stays on forever.

    /** The FIT invalid sentinel for this type's base type. */
    public val INVALID: UByte = UByte.MAX_VALUE
}
