/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `ble_device_type`.
 */
public enum class BleDeviceType(
    public val value: UByte,
) {
    CONNECTED_GPS(0u), // GPS that is provided over a proprietary bluetooth service
    HEART_RATE(1u),
    BIKE_POWER(2u),
    BIKE_SPEED_CADENCE(3u),
    BIKE_SPEED(4u),
    BIKE_CADENCE(5u),
    FOOTPOD(6u),
    BIKE_TRAINER(7u), // Indoor-Bike FTMS protocol

    /** Returned for any raw value not present in the profile. */
    INVALID(UByte.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UByte, BleDeviceType> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UByte): BleDeviceType =
            byValue[value] ?: INVALID
    }
}
