/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `brazilian_grading_scale`.
 */
public enum class BrazilianGradingScale(
    public val value: UByte,
) {
    _2(0u), // 2
    _3(1u), // 3
    _3C(2u), // 3c
    _4(3u), // 4
    _5A(4u), // 5a
    _5B(5u), // 5b
    _5C(6u), // 5c
    _6A(7u), // 6a
    _6B(8u), // 6b
    _6C(9u), // 6c
    _7A(10u), // 7a
    _7B(11u), // 7b
    _7C(12u), // 7c
    _8A(13u), // 8a
    _8B(14u), // 8b
    _8C(15u), // 8c
    _9A(16u), // 9a
    _9B(17u), // 9b
    _9C(18u), // 9c
    _10A(19u), // 10a
    _10B(20u), // 10b
    _10C(21u), // 10c
    _11A(22u), // 11a
    _11B(23u), // 11b
    _11C(24u), // 11c
    _12A(25u), // 12a
    _12B(26u), // 12b

    /** Returned for any raw value not present in the profile. */
    INVALID(UByte.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UByte, BrazilianGradingScale> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UByte): BrazilianGradingScale =
            byValue[value] ?: INVALID
    }
}
