/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `british_technical_grading_scale`.
 */
public enum class BritishTechnicalGradingScale(
    public val value: UByte,
) {
    _1(0u), // 1
    _2(1u), // 2
    _3(2u), // 3
    _4A(3u), // 4a
    _4B(4u), // 4b
    _4C(5u), // 4c
    _5A(6u), // 5a
    _5B(7u), // 5b
    _5C(8u), // 5c
    _6A(9u), // 6a
    _6B(10u), // 6b
    _6C(11u), // 6c
    _7A(12u), // 7a
    _7B(13u), // 7b
    _7C(14u), // 7c

    /** Returned for any raw value not present in the profile. */
    INVALID(UByte.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UByte, BritishTechnicalGradingScale> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UByte): BritishTechnicalGradingScale =
            byValue[value] ?: INVALID
    }
}
