/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.205.0Release
// Tag = production/release/21.205.0-0-gb3c261eb
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `chop_exercise_name`.
 */
public enum class ChopExerciseName(
    public val value: UShort,
) {
    CABLE_PULL_THROUGH(0u),
    CABLE_ROTATIONAL_LIFT(1u),
    CABLE_WOODCHOP(2u),
    CROSS_CHOP_TO_KNEE(3u),
    WEIGHTED_CROSS_CHOP_TO_KNEE(4u),
    DUMBBELL_CHOP(5u),
    HALF_KNEELING_ROTATION(6u),
    WEIGHTED_HALF_KNEELING_ROTATION(7u),
    HALF_KNEELING_ROTATIONAL_CHOP(8u),
    HALF_KNEELING_ROTATIONAL_REVERSE_CHOP(9u),
    HALF_KNEELING_STABILITY_CHOP(10u),
    HALF_KNEELING_STABILITY_REVERSE_CHOP(11u),
    KNEELING_ROTATIONAL_CHOP(12u),
    KNEELING_ROTATIONAL_REVERSE_CHOP(13u),
    KNEELING_STABILITY_CHOP(14u),
    KNEELING_WOODCHOPPER(15u),
    MEDICINE_BALL_WOOD_CHOPS(16u),
    POWER_SQUAT_CHOPS(17u),
    WEIGHTED_POWER_SQUAT_CHOPS(18u),
    STANDING_ROTATIONAL_CHOP(19u),
    STANDING_SPLIT_ROTATIONAL_CHOP(20u),
    STANDING_SPLIT_ROTATIONAL_REVERSE_CHOP(21u),
    STANDING_STABILITY_REVERSE_CHOP(22u),

    /** Returned for any raw value not present in the profile. */
    INVALID(UShort.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UShort, ChopExerciseName> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UShort): ChopExerciseName =
            byValue[value] ?: INVALID
    }
}
