/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `climb_grading_scale`.
 */
public enum class ClimbGradingScale(
    public val value: UByte,
) {
    YDS(0u),
    UIAA(1u),
    FRENCH(2u),
    BRITISH_ADJECTIVAL(3u),
    BRITISH_TECHNICAL(4u),
    EWBANK(5u),
    BRAZILIAN(6u),
    SAXON(7u),
    VERMIN(8u),
    FONT(9u),
    DANKYU(10u),
    YDS_PM(11u), // YDS Plus Minus Grading Scale

    /** Returned for any raw value not present in the profile. */
    INVALID(UByte.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UByte, ClimbGradingScale> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UByte): ClimbGradingScale =
            byValue[value] ?: INVALID
    }
}
