/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `comm_timeout_type`.
 */
public enum class CommTimeoutType(
    public val value: UShort,
) {
    WILDCARD_PAIRING_TIMEOUT(0u), // Timeout pairing to any device
    PAIRING_TIMEOUT(1u), // Timeout pairing to previously paired device
    CONNECTION_LOST(2u), // Temporary loss of communications
    CONNECTION_TIMEOUT(3u), // Connection closed due to extended bad communications

    /** Returned for any raw value not present in the profile. */
    INVALID(UShort.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UShort, CommTimeoutType> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UShort): CommTimeoutType =
            byValue[value] ?: INVALID
    }
}
