/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.213.0Release
// Tag = production/release/21.213.0-0-g9e10ea9c
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `course_capabilities`.
 */
public enum class CourseCapabilities(
    public val value: UInt,
) {
    PROCESSED(0x00000001u),
    VALID(0x00000002u),
    TIME(0x00000004u),
    DISTANCE(0x00000008u),
    POSITION(0x00000010u),
    HEART_RATE(0x00000020u),
    POWER(0x00000040u),
    CADENCE(0x00000080u),
    TRAINING(0x00000100u),
    NAVIGATION(0x00000200u),
    BIKEWAY(0x00000400u),
    AVIATION(0x00001000u), // Denote course files to be used as flight plans

    /** Returned for any raw value not present in the profile. */
    INVALID(UInt.MIN_VALUE),
    ;

    public companion object {
        private val byValue: Map<UInt, CourseCapabilities> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UInt): CourseCapabilities =
            byValue[value] ?: INVALID
    }
}
