/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.213.0Release
// Tag = production/release/21.213.0-0-g9e10ea9c
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `crunch_exercise_name`.
 */
public enum class CrunchExerciseName(
    public val value: UShort,
) {
    BICYCLE_CRUNCH(0u),
    CABLE_CRUNCH(1u),
    CIRCULAR_ARM_CRUNCH(2u),
    CROSSED_ARMS_CRUNCH(3u),
    WEIGHTED_CROSSED_ARMS_CRUNCH(4u),
    CROSS_LEG_REVERSE_CRUNCH(5u),
    WEIGHTED_CROSS_LEG_REVERSE_CRUNCH(6u),
    CRUNCH_CHOP(7u),
    WEIGHTED_CRUNCH_CHOP(8u),
    DOUBLE_CRUNCH(9u),
    WEIGHTED_DOUBLE_CRUNCH(10u),
    ELBOW_TO_KNEE_CRUNCH(11u),
    WEIGHTED_ELBOW_TO_KNEE_CRUNCH(12u),
    FLUTTER_KICKS(13u),
    WEIGHTED_FLUTTER_KICKS(14u),
    FOAM_ROLLER_REVERSE_CRUNCH_ON_BENCH(15u),
    WEIGHTED_FOAM_ROLLER_REVERSE_CRUNCH_ON_BENCH(16u),
    FOAM_ROLLER_REVERSE_CRUNCH_WITH_DUMBBELL(17u),
    FOAM_ROLLER_REVERSE_CRUNCH_WITH_MEDICINE_BALL(18u),
    FROG_PRESS(19u),
    HANGING_KNEE_RAISE_OBLIQUE_CRUNCH(20u),
    WEIGHTED_HANGING_KNEE_RAISE_OBLIQUE_CRUNCH(21u),
    HIP_CROSSOVER(22u),
    WEIGHTED_HIP_CROSSOVER(23u),
    HOLLOW_ROCK(24u),
    WEIGHTED_HOLLOW_ROCK(25u),
    INCLINE_REVERSE_CRUNCH(26u),
    WEIGHTED_INCLINE_REVERSE_CRUNCH(27u),
    KNEELING_CABLE_CRUNCH(28u),
    KNEELING_CROSS_CRUNCH(29u),
    WEIGHTED_KNEELING_CROSS_CRUNCH(30u),
    KNEELING_OBLIQUE_CABLE_CRUNCH(31u),
    KNEES_TO_ELBOW(32u),
    LEG_EXTENSIONS(33u),
    WEIGHTED_LEG_EXTENSIONS(34u),
    LEG_LEVERS(35u),
    MCGILL_CURL_UP(36u),
    WEIGHTED_MCGILL_CURL_UP(37u),
    MODIFIED_PILATES_ROLL_UP_WITH_BALL(38u),
    WEIGHTED_MODIFIED_PILATES_ROLL_UP_WITH_BALL(39u),
    PILATES_CRUNCH(40u),
    WEIGHTED_PILATES_CRUNCH(41u),
    PILATES_ROLL_UP_WITH_BALL(42u),
    WEIGHTED_PILATES_ROLL_UP_WITH_BALL(43u),
    RAISED_LEGS_CRUNCH(44u),
    WEIGHTED_RAISED_LEGS_CRUNCH(45u),
    REVERSE_CRUNCH(46u),
    WEIGHTED_REVERSE_CRUNCH(47u),
    REVERSE_CRUNCH_ON_A_BENCH(48u),
    WEIGHTED_REVERSE_CRUNCH_ON_A_BENCH(49u),
    REVERSE_CURL_AND_LIFT(50u),
    WEIGHTED_REVERSE_CURL_AND_LIFT(51u),
    ROTATIONAL_LIFT(52u),
    WEIGHTED_ROTATIONAL_LIFT(53u),
    SEATED_ALTERNATING_REVERSE_CRUNCH(54u),
    WEIGHTED_SEATED_ALTERNATING_REVERSE_CRUNCH(55u),
    SEATED_LEG_U(56u),
    WEIGHTED_SEATED_LEG_U(57u),
    SIDE_TO_SIDE_CRUNCH_AND_WEAVE(58u),
    WEIGHTED_SIDE_TO_SIDE_CRUNCH_AND_WEAVE(59u),
    SINGLE_LEG_REVERSE_CRUNCH(60u),
    WEIGHTED_SINGLE_LEG_REVERSE_CRUNCH(61u),
    SKATER_CRUNCH_CROSS(62u),
    WEIGHTED_SKATER_CRUNCH_CROSS(63u),
    STANDING_CABLE_CRUNCH(64u),
    STANDING_SIDE_CRUNCH(65u),
    STEP_CLIMB(66u),
    WEIGHTED_STEP_CLIMB(67u),
    SWISS_BALL_CRUNCH(68u),
    SWISS_BALL_REVERSE_CRUNCH(69u),
    WEIGHTED_SWISS_BALL_REVERSE_CRUNCH(70u),
    SWISS_BALL_RUSSIAN_TWIST(71u),
    WEIGHTED_SWISS_BALL_RUSSIAN_TWIST(72u),
    SWISS_BALL_SIDE_CRUNCH(73u),
    WEIGHTED_SWISS_BALL_SIDE_CRUNCH(74u),
    THORACIC_CRUNCHES_ON_FOAM_ROLLER(75u),
    WEIGHTED_THORACIC_CRUNCHES_ON_FOAM_ROLLER(76u),
    TRICEPS_CRUNCH(77u),
    WEIGHTED_BICYCLE_CRUNCH(78u),
    WEIGHTED_CRUNCH(79u),
    WEIGHTED_SWISS_BALL_CRUNCH(80u),
    TOES_TO_BAR(81u),
    WEIGHTED_TOES_TO_BAR(82u),
    CRUNCH(83u),
    STRAIGHT_LEG_CRUNCH_WITH_BALL(84u),
    LEG_CLIMB_CRUNCH(86u),

    /** Returned for any raw value not present in the profile. */
    INVALID(UShort.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UShort, CrunchExerciseName> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UShort): CrunchExerciseName =
            byValue[value] ?: INVALID
    }
}
