/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.213.0Release
// Tag = production/release/21.213.0-0-g9e10ea9c
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `curl_exercise_name`.
 */
public enum class CurlExerciseName(
    public val value: UShort,
) {
    ALTERNATING_DUMBBELL_BICEPS_CURL(0u),
    ALTERNATING_DUMBBELL_BICEPS_CURL_ON_SWISS_BALL(1u),
    ALTERNATING_INCLINE_DUMBBELL_BICEPS_CURL(2u),
    BARBELL_BICEPS_CURL(3u),
    BARBELL_REVERSE_WRIST_CURL(4u),
    BARBELL_WRIST_CURL(5u),
    BEHIND_THE_BACK_BARBELL_REVERSE_WRIST_CURL(6u),
    BEHIND_THE_BACK_ONE_ARM_CABLE_CURL(7u),
    CABLE_BICEPS_CURL(8u),
    CABLE_HAMMER_CURL(9u),
    CHEATING_BARBELL_BICEPS_CURL(10u),
    CLOSE_GRIP_EZ_BAR_BICEPS_CURL(11u),
    CROSS_BODY_DUMBBELL_HAMMER_CURL(12u),
    DEAD_HANG_BICEPS_CURL(13u),
    DECLINE_HAMMER_CURL(14u),
    DUMBBELL_BICEPS_CURL_WITH_STATIC_HOLD(15u),
    DUMBBELL_HAMMER_CURL(16u),
    DUMBBELL_REVERSE_WRIST_CURL(17u),
    DUMBBELL_WRIST_CURL(18u),
    EZ_BAR_PREACHER_CURL(19u),
    FORWARD_BEND_BICEPS_CURL(20u),
    HAMMER_CURL_TO_PRESS(21u),
    INCLINE_DUMBBELL_BICEPS_CURL(22u),
    INCLINE_OFFSET_THUMB_DUMBBELL_CURL(23u),
    KETTLEBELL_BICEPS_CURL(24u),
    LYING_CONCENTRATION_CABLE_CURL(25u),
    ONE_ARM_PREACHER_CURL(26u),
    PLATE_PINCH_CURL(27u),
    PREACHER_CURL_WITH_CABLE(28u),
    REVERSE_EZ_BAR_CURL(29u),
    REVERSE_GRIP_WRIST_CURL(30u),
    REVERSE_GRIP_BARBELL_BICEPS_CURL(31u),
    SEATED_ALTERNATING_DUMBBELL_BICEPS_CURL(32u),
    SEATED_DUMBBELL_BICEPS_CURL(33u),
    SEATED_REVERSE_DUMBBELL_CURL(34u),
    SPLIT_STANCE_OFFSET_PINKY_DUMBBELL_CURL(35u),
    STANDING_ALTERNATING_DUMBBELL_CURLS(36u),
    STANDING_DUMBBELL_BICEPS_CURL(37u),
    STANDING_EZ_BAR_BICEPS_CURL(38u),
    STATIC_CURL(39u),
    SWISS_BALL_DUMBBELL_OVERHEAD_TRICEPS_EXTENSION(40u),
    SWISS_BALL_EZ_BAR_PREACHER_CURL(41u),
    TWISTING_STANDING_DUMBBELL_BICEPS_CURL(42u),
    WIDE_GRIP_EZ_BAR_BICEPS_CURL(43u),
    ONE_ARM_CONCENTRATION_CURL(44u),
    STANDING_ZOTTMAN_BICEPS_CURL(45u),
    DUMBBELL_BICEPS_CURL(46u),
    DRAG_CURL_WHEELCHAIR(47u),
    DUMBBELL_BICEPS_CURL_WHEELCHAIR(48u),
    BOTTLE_CURL(49u),
    SEATED_BOTTLE_CURL(50u),

    /** Returned for any raw value not present in the profile. */
    INVALID(UShort.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UShort, CurlExerciseName> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UShort): CurlExerciseName =
            byValue[value] ?: INVALID
    }
}
