/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `dankyu_grading_scale`.
 */
public enum class DankyuGradingScale(
    public val value: UByte,
) {
    _7_KYUU(0u), // 7 kyuu
    _6_KYUU(1u), // 6 kyuu
    _5_KYUU(2u), // 5 kyuu
    _4_KYUU(3u), // 4 kyuu
    _3_KYUU(4u), // 3 kyuu
    _2_KYUU(5u), // 2 kyuu
    _1_KYUU(6u), // 1 kyuu
    _1_DAN(7u), // 1 dan
    _2_DAN(8u), // 2 dan
    _3_DAN(9u), // 3 dan
    _4_DAN(10u), // 4 dan
    _5_DAN(11u), // 5 dan

    /** Returned for any raw value not present in the profile. */
    INVALID(UByte.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UByte, DankyuGradingScale> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UByte): DankyuGradingScale =
            byValue[value] ?: INVALID
    }
}
