/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.213.0Release
// Tag = production/release/21.213.0-0-g9e10ea9c
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * Named values for the FIT profile type `device_index`.
 *
 * This type is not modelled as an enum: it is a bit mask or a scalar with named
 * thresholds, so values outside the list below are meaningful.
 */
public object DeviceIndexValues {
    public const val CREATOR: UByte = 0u // Creator of the file is always device index 0.

    /** The FIT invalid sentinel for this type's base type. */
    public val INVALID: UByte = UByte.MAX_VALUE
}
