/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `display_position`.
 */
public enum class DisplayPosition(
    public val value: UByte,
) {
    DEGREE(0u), // dd.dddddd
    DEGREE_MINUTE(1u), // dddmm.mmm
    DEGREE_MINUTE_SECOND(2u), // dddmmss
    AUSTRIAN_GRID(3u), // Austrian Grid (BMN)
    BRITISH_GRID(4u), // British National Grid
    DUTCH_GRID(5u), // Dutch grid system
    HUNGARIAN_GRID(6u), // Hungarian grid system
    FINNISH_GRID(7u), // Finnish grid system Zone3 KKJ27
    GERMAN_GRID(8u), // Gausss Krueger (German)
    ICELANDIC_GRID(9u), // Icelandic Grid
    INDONESIAN_EQUATORIAL(10u), // Indonesian Equatorial LCO
    INDONESIAN_IRIAN(11u), // Indonesian Irian LCO
    INDONESIAN_SOUTHERN(12u), // Indonesian Southern LCO
    INDIA_ZONE_0(13u), // India zone 0
    INDIA_ZONE_IA(14u), // India zone IA
    INDIA_ZONE_IB(15u), // India zone IB
    INDIA_ZONE_IIA(16u), // India zone IIA
    INDIA_ZONE_IIB(17u), // India zone IIB
    INDIA_ZONE_IIIA(18u), // India zone IIIA
    INDIA_ZONE_IIIB(19u), // India zone IIIB
    INDIA_ZONE_IVA(20u), // India zone IVA
    INDIA_ZONE_IVB(21u), // India zone IVB
    IRISH_TRANSVERSE(22u), // Irish Transverse Mercator
    IRISH_GRID(23u), // Irish Grid
    LORAN(24u), // Loran TD
    MAIDENHEAD_GRID(25u), // Maidenhead grid system
    MGRS_GRID(26u), // MGRS grid system
    NEW_ZEALAND_GRID(27u), // New Zealand grid system
    NEW_ZEALAND_TRANSVERSE(28u), // New Zealand Transverse Mercator
    QATAR_GRID(29u), // Qatar National Grid
    MODIFIED_SWEDISH_GRID(30u), // Modified RT-90 (Sweden)
    SWEDISH_GRID(31u), // RT-90 (Sweden)
    SOUTH_AFRICAN_GRID(32u), // South African Grid
    SWISS_GRID(33u), // Swiss CH-1903 grid
    TAIWAN_GRID(34u), // Taiwan Grid
    UNITED_STATES_GRID(35u), // United States National Grid
    UTM_UPS_GRID(36u), // UTM/UPS grid system
    WEST_MALAYAN(37u), // West Malayan RSO
    BORNEO_RSO(38u), // Borneo RSO
    ESTONIAN_GRID(39u), // Estonian grid system
    LATVIAN_GRID(40u), // Latvian Transverse Mercator
    SWEDISH_REF_99_GRID(41u), // Reference Grid 99 TM (Swedish)

    /** Returned for any raw value not present in the profile. */
    INVALID(UByte.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UByte, DisplayPosition> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UByte): DisplayPosition =
            byValue[value] ?: INVALID
    }
}
