/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `ewbank_grading_scale`.
 */
public enum class EwbankGradingScale(
    public val value: UByte,
) {
    _4(0u), // 4
    _5(1u), // 5
    _6(2u), // 6
    _7(3u), // 7
    _8(4u), // 8
    _9(5u), // 9
    _10(6u), // 10
    _11(7u), // 11
    _12(8u), // 12
    _13(9u), // 13
    _14(10u), // 14
    _15(11u), // 15
    _16(12u), // 16
    _17(13u), // 17
    _18(14u), // 18
    _19(15u), // 19
    _20(16u), // 20
    _21(17u), // 21
    _22(18u), // 22
    _23(19u), // 23
    _24(20u), // 24
    _25(21u), // 25
    _26(22u), // 26
    _27(23u), // 27
    _28(24u), // 28
    _29(25u), // 29
    _30(26u), // 30
    _31(27u), // 31
    _32(28u), // 32
    _33(29u), // 33
    _34(30u), // 34
    _35(31u), // 35
    _36(32u), // 36
    _37(33u), // 37
    _38(34u), // 38

    /** Returned for any raw value not present in the profile. */
    INVALID(UByte.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UByte, EwbankGradingScale> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UByte): EwbankGradingScale =
            byValue[value] ?: INVALID
    }
}
