/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.205.0Release
// Tag = production/release/21.205.0-0-gb3c261eb
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `exd_data_units`.
 */
public enum class ExdDataUnits(
    public val value: UByte,
) {
    NO_UNITS(0u),
    LAPS(1u),
    MILES_PER_HOUR(2u),
    KILOMETERS_PER_HOUR(3u),
    FEET_PER_HOUR(4u),
    METERS_PER_HOUR(5u),
    DEGREES_CELSIUS(6u),
    DEGREES_FARENHEIT(7u),
    ZONE(8u),
    GEAR(9u),
    RPM(10u),
    BPM(11u),
    DEGREES(12u),
    MILLIMETERS(13u),
    METERS(14u),
    KILOMETERS(15u),
    FEET(16u),
    YARDS(17u),
    KILOFEET(18u),
    MILES(19u),
    TIME(20u),
    ENUM_TURN_TYPE(21u),
    PERCENT(22u),
    WATTS(23u),
    WATTS_PER_KILOGRAM(24u),
    ENUM_BATTERY_STATUS(25u),
    ENUM_BIKE_LIGHT_BEAM_ANGLE_MODE(26u),
    ENUM_BIKE_LIGHT_BATTERY_STATUS(27u),
    ENUM_BIKE_LIGHT_NETWORK_CONFIG_TYPE(28u),
    LIGHTS(29u),
    SECONDS(30u),
    MINUTES(31u),
    HOURS(32u),
    CALORIES(33u),
    KILOJOULES(34u),
    MILLISECONDS(35u),
    SECOND_PER_MILE(36u),
    SECOND_PER_KILOMETER(37u),
    CENTIMETER(38u),
    ENUM_COURSE_POINT(39u),
    BRADIANS(40u),
    ENUM_SPORT(41u),
    INCHES_HG(42u),
    MM_HG(43u),
    MBARS(44u),
    HECTO_PASCALS(45u),
    FEET_PER_MIN(46u),
    METERS_PER_MIN(47u),
    METERS_PER_SEC(48u),
    EIGHT_CARDINAL(49u),

    /** Returned for any raw value not present in the profile. */
    INVALID(UByte.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UByte, ExdDataUnits> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UByte): ExdDataUnits =
            byValue[value] ?: INVALID
    }
}
