/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.213.0Release
// Tag = production/release/21.213.0-0-g9e10ea9c
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `exd_display_type`.
 */
public enum class ExdDisplayType(
    public val value: UByte,
) {
    NUMERICAL(0u),
    SIMPLE(1u),
    GRAPH(2u),
    BAR(3u),
    CIRCLE_GRAPH(4u),
    VIRTUAL_PARTNER(5u),
    BALANCE(6u),
    STRING_LIST(7u),
    STRING(8u),
    SIMPLE_DYNAMIC_ICON(9u),
    GAUGE(10u),

    /** Returned for any raw value not present in the profile. */
    INVALID(UByte.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UByte, ExdDisplayType> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UByte): ExdDisplayType =
            byValue[value] ?: INVALID
    }
}
