/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.213.0Release
// Tag = production/release/21.213.0-0-g9e10ea9c
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `exercise_category`.
 */
public enum class ExerciseCategory(
    public val value: UShort,
) {
    BENCH_PRESS(0u),
    CALF_RAISE(1u),
    CARDIO(2u),
    CARRY(3u),
    CHOP(4u),
    CORE(5u),
    CRUNCH(6u),
    CURL(7u),
    DEADLIFT(8u),
    FLYE(9u),
    HIP_RAISE(10u),
    HIP_STABILITY(11u),
    HIP_SWING(12u),
    HYPEREXTENSION(13u),
    LATERAL_RAISE(14u),
    LEG_CURL(15u),
    LEG_RAISE(16u),
    LUNGE(17u),
    OLYMPIC_LIFT(18u),
    PLANK(19u),
    PLYO(20u),
    PULL_UP(21u),
    PUSH_UP(22u),
    ROW(23u),
    SHOULDER_PRESS(24u),
    SHOULDER_STABILITY(25u),
    SHRUG(26u),
    SIT_UP(27u),
    SQUAT(28u),
    TOTAL_BODY(29u),
    TRICEPS_EXTENSION(30u),
    WARM_UP(31u),
    RUN(32u),
    BIKE(33u),
    CARDIO_SENSORS(34u), // Exercises within workouts that use GPS/sensors rather than rep counting
    MOVE(35u),
    POSE(36u),
    BANDED_EXERCISES(37u),
    BATTLE_ROPE(38u),
    ELLIPTICAL(39u),
    FLOOR_CLIMB(40u),
    INDOOR_BIKE(41u),
    INDOOR_ROW(42u),
    LADDER(43u),
    SANDBAG(44u),
    SLED(45u),
    SLEDGE_HAMMER(46u),
    STAIR_STEPPER(47u),
    SUSPENSION(49u),
    TIRE(50u),
    RUN_INDOOR(52u),
    BIKE_OUTDOOR(53u),
    UNKNOWN(65534u),

    /** Returned for any raw value not present in the profile. */
    INVALID(UShort.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UShort, ExerciseCategory> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UShort): ExerciseCategory =
            byValue[value] ?: INVALID
    }
}
