/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `flye_exercise_name`.
 */
public enum class FlyeExerciseName(
    public val value: UShort,
) {
    CABLE_CROSSOVER(0u),
    DECLINE_DUMBBELL_FLYE(1u),
    DUMBBELL_FLYE(2u),
    INCLINE_DUMBBELL_FLYE(3u),
    KETTLEBELL_FLYE(4u),
    KNEELING_REAR_FLYE(5u),
    SINGLE_ARM_STANDING_CABLE_REVERSE_FLYE(6u),
    SWISS_BALL_DUMBBELL_FLYE(7u),
    ARM_ROTATIONS(8u),
    HUG_A_TREE(9u),
    FACE_DOWN_INCLINE_REVERSE_FLYE(10u),
    INCLINE_REVERSE_FLYE(11u),
    REAR_DELT_FLY_WHEELCHAIR(12u),

    /** Returned for any raw value not present in the profile. */
    INVALID(UShort.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UShort, FlyeExerciseName> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UShort): FlyeExerciseName =
            byValue[value] ?: INVALID
    }
}
