/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `french_grading_scale`.
 */
public enum class FrenchGradingScale(
    public val value: UByte,
) {
    _1(0u), // 1
    _2(1u), // 2
    _3(2u), // 3
    _4A(3u), // 4a
    _4B(4u), // 4b
    _4C(5u), // 4c
    _5A(6u), // 5a
    _5B(7u), // 5b
    _5C(8u), // 5c
    _6A(9u), // 6a
    _6A_PLUS(10u), // 6a+
    _6B(11u), // 6b
    _6B_PLUS(12u), // 6b+
    _6C(13u), // 6c
    _6C_PLUS(14u), // 6c+
    _7A(15u), // 7a
    _7A_PLUS(16u), // 7a+
    _7B(17u), // 7b
    _7B_PLUS(18u), // 7b+
    _7C(19u), // 7c
    _7C_PLUS(20u), // 7c+
    _8A(21u), // 8a
    _8A_PLUS(22u), // 8a+
    _8B(23u), // 8b
    _8B_PLUS(24u), // 8b+
    _8C(25u), // 8c
    _8C_PLUS(26u), // 8c+
    _9A(27u), // 9a
    _9A_PLUS(28u), // 9a+
    _9B(29u), // 9b

    /** Returned for any raw value not present in the profile. */
    INVALID(UByte.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UByte, FrenchGradingScale> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UByte): FrenchGradingScale =
            byValue[value] ?: INVALID
    }
}
