/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `hip_raise_exercise_name`.
 */
public enum class HipRaiseExerciseName(
    public val value: UShort,
) {
    BARBELL_HIP_THRUST_ON_FLOOR(0u),
    BARBELL_HIP_THRUST_WITH_BENCH(1u),
    BENT_KNEE_SWISS_BALL_REVERSE_HIP_RAISE(2u),
    WEIGHTED_BENT_KNEE_SWISS_BALL_REVERSE_HIP_RAISE(3u),
    BRIDGE_WITH_LEG_EXTENSION(4u),
    WEIGHTED_BRIDGE_WITH_LEG_EXTENSION(5u),
    CLAM_BRIDGE(6u),
    FRONT_KICK_TABLETOP(7u),
    WEIGHTED_FRONT_KICK_TABLETOP(8u),
    HIP_EXTENSION_AND_CROSS(9u),
    WEIGHTED_HIP_EXTENSION_AND_CROSS(10u),
    HIP_RAISE(11u),
    WEIGHTED_HIP_RAISE(12u),
    HIP_RAISE_WITH_FEET_ON_SWISS_BALL(13u),
    WEIGHTED_HIP_RAISE_WITH_FEET_ON_SWISS_BALL(14u),
    HIP_RAISE_WITH_HEAD_ON_BOSU_BALL(15u),
    WEIGHTED_HIP_RAISE_WITH_HEAD_ON_BOSU_BALL(16u),
    HIP_RAISE_WITH_HEAD_ON_SWISS_BALL(17u),
    WEIGHTED_HIP_RAISE_WITH_HEAD_ON_SWISS_BALL(18u),
    HIP_RAISE_WITH_KNEE_SQUEEZE(19u),
    WEIGHTED_HIP_RAISE_WITH_KNEE_SQUEEZE(20u),
    INCLINE_REAR_LEG_EXTENSION(21u),
    WEIGHTED_INCLINE_REAR_LEG_EXTENSION(22u),
    KETTLEBELL_SWING(23u),
    MARCHING_HIP_RAISE(24u),
    WEIGHTED_MARCHING_HIP_RAISE(25u),
    MARCHING_HIP_RAISE_WITH_FEET_ON_A_SWISS_BALL(26u),
    WEIGHTED_MARCHING_HIP_RAISE_WITH_FEET_ON_A_SWISS_BALL(27u),
    REVERSE_HIP_RAISE(28u),
    WEIGHTED_REVERSE_HIP_RAISE(29u),
    SINGLE_LEG_HIP_RAISE(30u),
    WEIGHTED_SINGLE_LEG_HIP_RAISE(31u),
    SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_BENCH(32u),
    WEIGHTED_SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_BENCH(33u),
    SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_BOSU_BALL(34u),
    WEIGHTED_SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_BOSU_BALL(35u),
    SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_FOAM_ROLLER(36u),
    WEIGHTED_SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_FOAM_ROLLER(37u),
    SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_MEDICINE_BALL(38u),
    WEIGHTED_SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_MEDICINE_BALL(39u),
    SINGLE_LEG_HIP_RAISE_WITH_HEAD_ON_BOSU_BALL(40u),
    WEIGHTED_SINGLE_LEG_HIP_RAISE_WITH_HEAD_ON_BOSU_BALL(41u),
    WEIGHTED_CLAM_BRIDGE(42u),
    SINGLE_LEG_SWISS_BALL_HIP_RAISE_AND_LEG_CURL(43u),
    CLAMS(44u),
    INNER_THIGH_CIRCLES(45u), // Deprecated do not use
    INNER_THIGH_SIDE_LIFT(46u), // Deprecated do not use
    LEG_CIRCLES(47u),
    LEG_LIFT(48u),
    LEG_LIFT_IN_EXTERNAL_ROTATION(49u),

    /** Returned for any raw value not present in the profile. */
    INVALID(UShort.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UShort, HipRaiseExerciseName> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UShort): HipRaiseExerciseName =
            byValue[value] ?: INVALID
    }
}
