/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `indoor_bike_exercise_name`.
 */
public enum class IndoorBikeExerciseName(
    public val value: UShort,
) {
    AIR_BIKE(0u),
    ASSAULT_BIKE(1u),
    STATIONARY_BIKE(3u),

    /** Returned for any raw value not present in the profile. */
    INVALID(UShort.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UShort, IndoorBikeExerciseName> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UShort): IndoorBikeExerciseName =
            byValue[value] ?: INVALID
    }
}
