/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `lateral_raise_exercise_name`.
 */
public enum class LateralRaiseExerciseName(
    public val value: UShort,
) {
    _45_DEGREE_CABLE_EXTERNAL_ROTATION(0u),
    ALTERNATING_LATERAL_RAISE_WITH_STATIC_HOLD(1u),
    BAR_MUSCLE_UP(2u),
    BENT_OVER_LATERAL_RAISE(3u),
    CABLE_DIAGONAL_RAISE(4u),
    CABLE_FRONT_RAISE(5u),
    CALORIE_ROW(6u),
    COMBO_SHOULDER_RAISE(7u),
    DUMBBELL_DIAGONAL_RAISE(8u),
    DUMBBELL_V_RAISE(9u),
    FRONT_RAISE(10u),
    LEANING_DUMBBELL_LATERAL_RAISE(11u),
    LYING_DUMBBELL_RAISE(12u),
    MUSCLE_UP(13u),
    ONE_ARM_CABLE_LATERAL_RAISE(14u),
    OVERHAND_GRIP_REAR_LATERAL_RAISE(15u),
    PLATE_RAISES(16u),
    RING_DIP(17u),
    WEIGHTED_RING_DIP(18u),
    RING_MUSCLE_UP(19u),
    WEIGHTED_RING_MUSCLE_UP(20u),
    ROPE_CLIMB(21u),
    WEIGHTED_ROPE_CLIMB(22u),
    SCAPTION(23u),
    SEATED_LATERAL_RAISE(24u),
    SEATED_REAR_LATERAL_RAISE(25u),
    SIDE_LYING_LATERAL_RAISE(26u),
    STANDING_LIFT(27u),
    SUSPENDED_ROW(28u),
    UNDERHAND_GRIP_REAR_LATERAL_RAISE(29u),
    WALL_SLIDE(30u),
    WEIGHTED_WALL_SLIDE(31u),
    ARM_CIRCLES(32u),
    SHAVING_THE_HEAD(33u),
    DUMBBELL_LATERAL_RAISE(34u),
    RING_DIP_KIPPING(36u),
    WALL_WALK(37u),
    DUMBBELL_FRONT_RAISE_WHEELCHAIR(38u),
    DUMBBELL_LATERAL_RAISE_WHEELCHAIR(39u),
    POLE_DOUBLE_ARM_OVERHEAD_AND_FORWARD_WHEELCHAIR(40u),
    POLE_STRAIGHT_ARM_OVERHEAD_WHEELCHAIR(41u),

    /** Returned for any raw value not present in the profile. */
    INVALID(UShort.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UShort, LateralRaiseExerciseName> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UShort): LateralRaiseExerciseName =
            byValue[value] ?: INVALID
    }
}
