/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.205.0Release
// Tag = production/release/21.205.0-0-gb3c261eb
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `leg_curl_exercise_name`.
 */
public enum class LegCurlExerciseName(
    public val value: UShort,
) {
    LEG_CURL(0u),
    WEIGHTED_LEG_CURL(1u),
    GOOD_MORNING(2u),
    SEATED_BARBELL_GOOD_MORNING(3u),
    SINGLE_LEG_BARBELL_GOOD_MORNING(4u),
    SINGLE_LEG_SLIDING_LEG_CURL(5u),
    SLIDING_LEG_CURL(6u),
    SPLIT_BARBELL_GOOD_MORNING(7u),
    SPLIT_STANCE_EXTENSION(8u),
    STAGGERED_STANCE_GOOD_MORNING(9u),
    SWISS_BALL_HIP_RAISE_AND_LEG_CURL(10u),
    ZERCHER_GOOD_MORNING(11u),
    BAND_GOOD_MORNING(12u),
    BAR_GOOD_MORNING(13u),

    /** Returned for any raw value not present in the profile. */
    INVALID(UShort.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UShort, LegCurlExerciseName> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UShort): LegCurlExerciseName =
            byValue[value] ?: INVALID
    }
}
