/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.213.0Release
// Tag = production/release/21.213.0-0-g9e10ea9c
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `move_exercise_name`.
 */
public enum class MoveExerciseName(
    public val value: UShort,
) {
    ARCH_AND_CURL(0u),
    ARM_CIRCLES_WITH_BALL_BAND_AND_WEIGHT(1u),
    ARM_STRETCH(2u),
    BACK_MASSAGE(3u),
    BELLY_BREATHING(4u),
    BRIDGE_WITH_BALL(5u),
    DIAMOND_LEG_CRUNCH(6u),
    DIAMOND_LEG_LIFT(7u),
    EIGHT_POINT_SHOULDER_OPENER(8u),
    FOOT_ROLLING(9u),
    FOOTWORK(10u),
    FOOTWORK_ON_DISC(11u),
    FORWARD_FOLD(12u),
    FROG_WITH_BAND(13u),
    HALF_ROLL_UP(14u),
    HAMSTRING_CURL(15u),
    HAMSTRING_STRETCH(16u),
    HIP_STRETCH(17u),
    HUG_A_TREE_WITH_BALL_BAND_AND_WEIGHT(18u),
    KNEE_CIRCLES(19u),
    KNEE_FOLDS_ON_DISC(20u),
    LATERAL_FLEXION(21u),
    LEG_STRETCH_WITH_BAND(22u),
    LEG_STRETCH_WITH_LEG_CIRCLES(23u),
    LOWER_LIFT_ON_DISC(24u),
    LUNGE_SQUAT(25u),
    LUNGES_WITH_KNEE_LIFT(26u),
    MERMAID_STRETCH(27u),
    NEUTRAL_PELVIC_POSITION(28u),
    PELVIC_CLOCKS_ON_DISC(29u),
    PILATES_PLIE_SQUATS_PARALLEL_TURNED_OUT_FLAT_AND_HEELS_WITH_CHAIR(30u),
    PIRIFORMIS_STRETCH(31u),
    PLANK_KNEE_CROSSES(32u),
    PLANK_KNEE_PULLS(33u),
    PLANK_UP_DOWNS(34u),
    PRAYER_MUDRA(35u),
    PSOAS_LUNGE_STRETCH(36u),
    RIBCAGE_BREATHING(37u),
    ROLL_DOWN(38u),
    ROLL_UP_WITH_WEIGHT_AND_BAND(39u),
    SAW(40u),
    SCAPULAR_STABILIZATION(41u),
    SCISSORS_ON_DISC(42u),
    SEATED_HIP_STRETCHUP(43u),
    SEATED_TWIST(44u),
    SHAVING_THE_HEAD_WITH_BALL_BAND_AND_WEIGHT(45u),
    SPINAL_TWIST(46u),
    SPINAL_TWIST_STRETCH(47u),
    SPINE_STRETCH_FORWARD(48u),
    SQUAT_OPEN_ARM_TWIST_POSE(49u),
    SQUATS_WITH_BALL(50u),
    STAND_AND_HANG(51u),
    STANDING_SIDE_STRETCH(52u),
    STANDING_SINGLE_LEG_FORWARD_BEND_WITH_IT_BAND_OPENER(53u),
    STRAIGHT_LEG_CRUNCH_WITH_LEG_LIFT(54u),
    STRAIGHT_LEG_CRUNCH_WITH_LEG_LIFT_WITH_BALL(55u),
    STRAIGHT_LEG_CRUNCH_WITH_LEGS_CROSSED(56u),
    STRAIGHT_LEG_CRUNCH_WITH_LEGS_CROSSED_WITH_BALL(57u),
    STRAIGHT_LEG_DIAGONAL_CRUNCH(58u),
    STRAIGHT_LEG_DIAGONAL_CRUNCH_WITH_BALL(59u),
    TAILBONE_CURL(60u),
    THROAT_LOCK(61u),
    TICK_TOCK_SIDE_ROLL(62u),
    TWIST(63u),
    V_LEG_CRUNCHES(64u),
    V_SIT(65u),
    FORWARD_FOLD_WHEELCHAIR(66u),
    FORWARD_FOLD_PLUS_WHEELCHAIR(67u),
    ARM_CIRCLES_LOW_FORWARD_WHEELCHAIR(68u),
    ARM_CIRCLES_MID_FORWARD_WHEELCHAIR(69u),
    ARM_CIRCLES_HIGH_FORWARD_WHEELCHAIR(70u),
    ARM_CIRCLES_LOW_BACKWARD_WHEELCHAIR(71u),
    ARM_CIRCLES_MID_BACKWARD_WHEELCHAIR(72u),
    ARM_CIRCLES_HIGH_BACKWARD_WHEELCHAIR(73u),
    CORE_TWISTS_WHEELCHAIR(74u),
    ARM_RAISE_WHEELCHAIR(75u),
    CHEST_EXPAND_WHEELCHAIR(76u),
    ARM_EXTEND_WHEELCHAIR(77u),
    FORWARD_BEND_WHEELCHAIR(78u),
    TOE_TOUCH_WHEELCHAIR(79u),
    EXTENDED_TOE_TOUCH_WHEELCHAIR(80u),
    SEATED_ARM_CIRCLES(81u),
    TRUNK_ROTATIONS(82u),
    SEATED_TRUNK_ROTATIONS(83u),
    TOE_TOUCH(84u),

    /** Returned for any raw value not present in the profile. */
    INVALID(UShort.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UShort, MoveExerciseName> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UShort): MoveExerciseName =
            byValue[value] ?: INVALID
    }
}
