/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.205.0Release
// Tag = production/release/21.205.0-0-gb3c261eb
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `nap_period_feedback`.
 */
public enum class NapPeriodFeedback(
    public val value: UByte,
) {
    NONE(0u),
    MULTIPLE_NAPS_DURING_DAY(1u),
    JETLAG_IDEAL_TIMING_IDEAL_DURATION(2u),
    JETLAG_IDEAL_TIMING_LONG_DURATION(3u),
    JETLAG_LATE_TIMING_IDEAL_DURATION(4u),
    JETLAG_LATE_TIMING_LONG_DURATION(5u),
    IDEAL_TIMING_IDEAL_DURATION_LOW_NEED(6u),
    IDEAL_TIMING_IDEAL_DURATION_HIGH_NEED(7u),
    IDEAL_TIMING_LONG_DURATION_LOW_NEED(8u),
    IDEAL_TIMING_LONG_DURATION_HIGH_NEED(9u),
    LATE_TIMING_IDEAL_DURATION_LOW_NEED(10u),
    LATE_TIMING_IDEAL_DURATION_HIGH_NEED(11u),
    LATE_TIMING_LONG_DURATION_LOW_NEED(12u),
    LATE_TIMING_LONG_DURATION_HIGH_NEED(13u),
    IDEAL_DURATION_LOW_NEED(14u),
    IDEAL_DURATION_HIGH_NEED(15u),
    LONG_DURATION_LOW_NEED(16u),
    LONG_DURATION_HIGH_NEED(17u),

    /** Returned for any raw value not present in the profile. */
    INVALID(UByte.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UByte, NapPeriodFeedback> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UByte): NapPeriodFeedback =
            byValue[value] ?: INVALID
    }
}
