/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.205.0Release
// Tag = production/release/21.205.0-0-gb3c261eb
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `plyo_exercise_name`.
 */
public enum class PlyoExerciseName(
    public val value: UShort,
) {
    ALTERNATING_JUMP_LUNGE(0u),
    WEIGHTED_ALTERNATING_JUMP_LUNGE(1u),
    BARBELL_JUMP_SQUAT(2u),
    BODY_WEIGHT_JUMP_SQUAT(3u),
    WEIGHTED_JUMP_SQUAT(4u),
    CROSS_KNEE_STRIKE(5u),
    WEIGHTED_CROSS_KNEE_STRIKE(6u),
    DEPTH_JUMP(7u),
    WEIGHTED_DEPTH_JUMP(8u),
    DUMBBELL_JUMP_SQUAT(9u),
    DUMBBELL_SPLIT_JUMP(10u),
    FRONT_KNEE_STRIKE(11u),
    WEIGHTED_FRONT_KNEE_STRIKE(12u),
    HIGH_BOX_JUMP(13u),
    WEIGHTED_HIGH_BOX_JUMP(14u),
    ISOMETRIC_EXPLOSIVE_BODY_WEIGHT_JUMP_SQUAT(15u),
    WEIGHTED_ISOMETRIC_EXPLOSIVE_JUMP_SQUAT(16u),
    LATERAL_LEAP_AND_HOP(17u),
    WEIGHTED_LATERAL_LEAP_AND_HOP(18u),
    LATERAL_PLYO_SQUATS(19u),
    WEIGHTED_LATERAL_PLYO_SQUATS(20u),
    LATERAL_SLIDE(21u),
    WEIGHTED_LATERAL_SLIDE(22u),
    MEDICINE_BALL_OVERHEAD_THROWS(23u),
    MEDICINE_BALL_SIDE_THROW(24u),
    MEDICINE_BALL_SLAM(25u),
    SIDE_TO_SIDE_MEDICINE_BALL_THROWS(26u),
    SIDE_TO_SIDE_SHUFFLE_JUMP(27u),
    WEIGHTED_SIDE_TO_SIDE_SHUFFLE_JUMP(28u),
    SQUAT_JUMP_ONTO_BOX(29u),
    WEIGHTED_SQUAT_JUMP_ONTO_BOX(30u),
    SQUAT_JUMPS_IN_AND_OUT(31u),
    WEIGHTED_SQUAT_JUMPS_IN_AND_OUT(32u),
    BOX_JUMP(33u),
    BOX_JUMP_OVERS(34u),
    BOX_JUMP_OVERS_OVER_THE_BOX(35u),
    STAR_JUMP_SQUATS(36u),
    JUMP_SQUAT(37u),

    /** Returned for any raw value not present in the profile. */
    INVALID(UShort.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UShort, PlyoExerciseName> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UShort): PlyoExerciseName =
            byValue[value] ?: INVALID
    }
}
