/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.213.0Release
// Tag = production/release/21.213.0-0-g9e10ea9c
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `sandbag_exercise_name`.
 */
public enum class SandbagExerciseName(
    public val value: UShort,
) {
    AROUND_THE_WORLD(0u),
    BACK_SQUAT(1u),
    BEAR_CRAWL_PULL_THROUGH(2u),
    BEAR_HUG_SQUAT(3u),
    CLEAN(4u),
    CLEAN_AND_PRESS(5u),
    CURL(6u),
    FRONT_CARRY(7u),
    FRONT_SQUAT(8u),
    LUNGE(9u),
    OVERHEAD_PRESS(10u),
    PLANK_PULL_THROUGH(11u),
    ROTATIONAL_LUNGE(12u),
    ROW(13u),
    RUSSIAN_TWIST(14u),
    SHOULDERING(15u),
    SHOVELING(16u),
    SIDE_LUNGE(17u),
    SPRINT(18u),
    ZERCHER_SQUAT(19u),

    /** Returned for any raw value not present in the profile. */
    INVALID(UShort.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UShort, SandbagExerciseName> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UShort): SandbagExerciseName =
            byValue[value] ?: INVALID
    }
}
