/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `saxon_grading_scale`.
 */
public enum class SaxonGradingScale(
    public val value: UByte,
) {
    I(0u), // I
    II(1u), // II
    III(2u), // III
    IV(3u), // IV
    V(4u), // V
    VI(5u), // VI
    VII_A(6u), // VIIa
    VII_B(7u), // VIIb
    VII_C(8u), // VIIc
    VIII_A(9u), // VIIIa
    VIII_B(10u), // VIIIb
    VIII_C(11u), // VIIIc
    IX_A(12u), // IXa
    IX_B(13u), // IXb
    IX_C(14u), // IXc
    X_A(15u), // Xa
    X_B(16u), // Xb
    X_C(17u), // Xc
    XI_A(18u), // XIa
    XI_B(19u), // XIb
    XI_C(20u), // XIc
    XII_A(21u), // XIIa
    XII_B(22u), // XIIb
    XII_C(23u), // XIIc

    /** Returned for any raw value not present in the profile. */
    INVALID(UByte.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UByte, SaxonGradingScale> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UByte): SaxonGradingScale =
            byValue[value] ?: INVALID
    }
}
