/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.213.0Release
// Tag = production/release/21.213.0-0-g9e10ea9c
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `segment_leaderboard_type`.
 */
public enum class SegmentLeaderboardType(
    public val value: UByte,
) {
    OVERALL(0u),
    PERSONAL_BEST(1u),
    CONNECTIONS(2u),
    GROUP(3u),
    CHALLENGER(4u),
    KOM(5u),
    QOM(6u),
    PR(7u),
    GOAL(8u),
    CARROT(9u),
    CLUB_LEADER(10u),
    RIVAL(11u),
    LAST(12u),
    RECENT_BEST(13u),
    COURSE_RECORD(14u),

    /** Returned for any raw value not present in the profile. */
    INVALID(UByte.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UByte, SegmentLeaderboardType> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UByte): SegmentLeaderboardType =
            byValue[value] ?: INVALID
    }
}
