/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `shoulder_stability_exercise_name`.
 */
public enum class ShoulderStabilityExerciseName(
    public val value: UShort,
) {
    _90_DEGREE_CABLE_EXTERNAL_ROTATION(0u),
    BAND_EXTERNAL_ROTATION(1u),
    BAND_INTERNAL_ROTATION(2u),
    BENT_ARM_LATERAL_RAISE_AND_EXTERNAL_ROTATION(3u),
    CABLE_EXTERNAL_ROTATION(4u),
    DUMBBELL_FACE_PULL_WITH_EXTERNAL_ROTATION(5u),
    FLOOR_I_RAISE(6u),
    WEIGHTED_FLOOR_I_RAISE(7u),
    FLOOR_T_RAISE(8u),
    WEIGHTED_FLOOR_T_RAISE(9u),
    FLOOR_Y_RAISE(10u),
    WEIGHTED_FLOOR_Y_RAISE(11u),
    INCLINE_I_RAISE(12u),
    WEIGHTED_INCLINE_I_RAISE(13u),
    INCLINE_L_RAISE(14u),
    WEIGHTED_INCLINE_L_RAISE(15u),
    INCLINE_T_RAISE(16u),
    WEIGHTED_INCLINE_T_RAISE(17u),
    INCLINE_W_RAISE(18u),
    WEIGHTED_INCLINE_W_RAISE(19u),
    INCLINE_Y_RAISE(20u),
    WEIGHTED_INCLINE_Y_RAISE(21u),
    LYING_EXTERNAL_ROTATION(22u),
    SEATED_DUMBBELL_EXTERNAL_ROTATION(23u),
    STANDING_L_RAISE(24u),
    SWISS_BALL_I_RAISE(25u),
    WEIGHTED_SWISS_BALL_I_RAISE(26u),
    SWISS_BALL_T_RAISE(27u),
    WEIGHTED_SWISS_BALL_T_RAISE(28u),
    SWISS_BALL_W_RAISE(29u),
    WEIGHTED_SWISS_BALL_W_RAISE(30u),
    SWISS_BALL_Y_RAISE(31u),
    WEIGHTED_SWISS_BALL_Y_RAISE(32u),
    CABLE_INTERNAL_ROTATION(33u),
    LYING_INTERNAL_ROTATION(34u),
    SEATED_DUMBBELL_INTERNAL_ROTATION(35u),

    /** Returned for any raw value not present in the profile. */
    INVALID(UShort.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UShort, ShoulderStabilityExerciseName> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UShort): ShoulderStabilityExerciseName =
            byValue[value] ?: INVALID
    }
}
