/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `sport_bits_5`.
 *
 * Bit field corresponding to sport enum type (1 << (sport-40)).
 */
public enum class SportBits5(
    public val value: UByte,
) {
    WATER_SKIING(0x01u),
    KAYAKING(0x02u),
    RAFTING(0x04u),
    WINDSURFING(0x08u),
    KITESURFING(0x10u),
    TACTICAL(0x20u),
    JUMPMASTER(0x40u),
    BOXING(0x80u),

    /** Returned for any raw value not present in the profile. */
    INVALID(UByte.MIN_VALUE),
    ;

    public companion object {
        private val byValue: Map<UByte, SportBits5> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UByte): SportBits5 =
            byValue[value] ?: INVALID
    }
}
