/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.205.0Release
// Tag = production/release/21.205.0-0-gb3c261eb
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `sport_bits_6`.
 *
 * Bit field corresponding to sport enum type (1 << (sport-48)).
 */
public enum class SportBits6(
    public val value: UByte,
) {
    FLOOR_CLIMBING(0x01u),

    /** Returned for any raw value not present in the profile. */
    INVALID(UByte.MIN_VALUE),
    ;

    public companion object {
        private val byValue: Map<UByte, SportBits6> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UByte): SportBits6 =
            byValue[value] ?: INVALID
    }
}
