/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.213.0Release
// Tag = production/release/21.213.0-0-g9e10ea9c
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `sport_event`.
 */
public enum class SportEvent(
    public val value: UByte,
) {
    UNCATEGORIZED(0u),
    GEOCACHING(1u),
    FITNESS(2u),
    RECREATION(3u),
    RACE(4u),
    SPECIAL_EVENT(5u),
    TRAINING(6u),
    TRANSPORTATION(7u),
    TOURING(8u),

    /** Returned for any raw value not present in the profile. */
    INVALID(UByte.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UByte, SportEvent> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UByte): SportEvent =
            byValue[value] ?: INVALID
    }
}
