/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.205.0Release
// Tag = production/release/21.205.0-0-gb3c261eb
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `sub_sport`.
 */
public enum class SubSport(
    public val value: UByte,
) {
    GENERIC(0u),
    TREADMILL(1u), // Run/Fitness Equipment
    STREET(2u), // Run
    TRAIL(3u), // Run
    TRACK(4u), // Run
    SPIN(5u), // Cycling
    INDOOR_CYCLING(6u), // Cycling/Fitness Equipment
    ROAD(7u), // Cycling
    MOUNTAIN(8u), // Cycling
    DOWNHILL(9u), // Cycling
    RECUMBENT(10u), // Cycling
    CYCLOCROSS(11u), // Cycling
    HAND_CYCLING(12u), // Cycling
    TRACK_CYCLING(13u), // Cycling
    INDOOR_ROWING(14u), // Fitness Equipment
    ELLIPTICAL(15u), // Fitness Equipment
    STAIR_CLIMBING(16u), // Fitness Equipment
    LAP_SWIMMING(17u), // Swimming
    OPEN_WATER(18u), // Swimming
    FLEXIBILITY_TRAINING(19u), // Training
    STRENGTH_TRAINING(20u), // Training
    WARM_UP(21u), // Tennis
    MATCH(22u), // Tennis
    EXERCISE(23u), // Tennis
    CHALLENGE(24u),
    INDOOR_SKIING(25u), // Fitness Equipment
    CARDIO_TRAINING(26u), // Training
    INDOOR_WALKING(27u), // Walking/Fitness Equipment
    E_BIKE_FITNESS(28u), // E-Biking
    BMX(29u), // Cycling
    CASUAL_WALKING(30u), // Walking
    SPEED_WALKING(31u), // Walking
    BIKE_TO_RUN_TRANSITION(32u), // Transition
    RUN_TO_BIKE_TRANSITION(33u), // Transition
    SWIM_TO_BIKE_TRANSITION(34u), // Transition
    ATV(35u), // Motorcycling
    MOTOCROSS(36u), // Motorcycling
    BACKCOUNTRY(37u), // Alpine Skiing/Snowboarding
    RESORT(38u), // Alpine Skiing/Snowboarding
    RC_DRONE(39u), // Flying
    WINGSUIT(40u), // Flying
    WHITEWATER(41u), // Kayaking/Rafting
    SKATE_SKIING(42u), // Cross Country Skiing
    YOGA(43u), // Training
    PILATES(44u), // Fitness Equipment
    INDOOR_RUNNING(45u), // Run
    GRAVEL_CYCLING(46u), // Cycling
    E_BIKE_MOUNTAIN(47u), // Cycling
    COMMUTING(48u), // Cycling
    MIXED_SURFACE(49u), // Cycling
    NAVIGATE(50u),
    TRACK_ME(51u),
    MAP(52u),
    SINGLE_GAS_DIVING(53u), // Diving
    MULTI_GAS_DIVING(54u), // Diving
    GAUGE_DIVING(55u), // Diving
    APNEA_DIVING(56u), // Diving
    APNEA_HUNTING(57u), // Diving
    VIRTUAL_ACTIVITY(58u),
    OBSTACLE(59u), // Used for events where participants run, crawl through mud, climb over walls, etc.
    BREATHING(62u),
    CCR_DIVING(63u), // Diving w/ closed circuit rebreather
    SAIL_RACE(65u), // Sailing
    EXPEDITION(66u), // Generic
    ULTRA(67u), // Ultramarathon
    INDOOR_CLIMBING(68u), // Climbing
    BOULDERING(69u), // Climbing
    HIIT(70u), // High Intensity Interval Training
    INDOOR_GRINDING(71u), // Sailing position, operating manual winches to power boat controls
    HUNTING_WITH_DOGS(72u), // Hunting
    AMRAP(73u), // HIIT
    EMOM(74u), // HIIT
    TABATA(75u), // HIIT
    ESPORT(77u), // Video Gaming, Cycling, etc.
    TRIATHLON(78u), // Multisport
    DUATHLON(79u), // Multisport
    BRICK(80u), // Multisport
    SWIM_RUN(81u), // Multisport
    ADVENTURE_RACE(82u), // Multisport
    TRUCKER_WORKOUT(83u), // DEZL trucker workout training sport
    PICKLEBALL(84u), // Racket
    PADEL(85u), // Racket
    INDOOR_WHEELCHAIR_WALK(86u),
    INDOOR_WHEELCHAIR_RUN(87u),
    INDOOR_HAND_CYCLING(88u),
    FIELD(90u), // Hockey
    ICE(91u), // Hockey
    ULTIMATE(92u), // Disc
    PLATFORM(93u), // Racket
    SQUASH(94u), // Racket
    BADMINTON(95u), // Racket
    RACQUETBALL(96u), // Racket
    TABLE_TENNIS(97u), // Racket
    OVERLAND(98u),
    TROLLING_MOTOR(99u), // Generic
    FLY_CANOPY(110u), // Flying
    FLY_PARAGLIDE(111u), // Flying
    FLY_PARAMOTOR(112u), // Flying
    FLY_PRESSURIZED(113u), // Flying
    FLY_NAVIGATE(114u), // Flying
    FLY_TIMER(115u), // Flying
    FLY_ALTIMETER(116u), // Flying
    FLY_WX(117u), // Flying
    FLY_VFR(118u), // Flying
    FLY_IFR(119u), // Flying
    DYNAMIC_APNEA(121u),
    ENDURO(123u), // Cycling
    RUCKING(124u), // Hiking
    RALLY(125u), // Motor sports
    POOL_TRIATHLON(126u), // Multisport
    E_BIKE_ENDURO(127u), // Cycling
    ALL(254u),

    /** Returned for any raw value not present in the profile. */
    INVALID(UByte.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UByte, SubSport> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UByte): SubSport =
            byValue[value] ?: INVALID
    }
}
