/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.205.0Release
// Tag = production/release/21.205.0-0-gb3c261eb
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `swim_stroke`.
 */
public enum class SwimStroke(
    public val value: UByte,
) {
    FREESTYLE(0u),
    BACKSTROKE(1u),
    BREASTSTROKE(2u),
    BUTTERFLY(3u),
    DRILL(4u),
    MIXED(5u),
    IM(6u), // IM is a mixed interval containing the same number of lengths for each of: Butterfly, Backstroke, Breaststroke, Freestyle, swam in that order.
    IM_BY_ROUND(7u), // For repeated workout steps, a new individual medly stroke is used for each round.
    RIMO(8u), // Reverse IM Order

    /** Returned for any raw value not present in the profile. */
    INVALID(UByte.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UByte, SwimStroke> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UByte): SwimStroke =
            byValue[value] ?: INVALID
    }
}
