/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `total_body_exercise_name`.
 */
public enum class TotalBodyExerciseName(
    public val value: UShort,
) {
    BURPEE(0u),
    WEIGHTED_BURPEE(1u),
    BURPEE_BOX_JUMP(2u),
    WEIGHTED_BURPEE_BOX_JUMP(3u),
    HIGH_PULL_BURPEE(4u),
    MAN_MAKERS(5u),
    ONE_ARM_BURPEE(6u),
    SQUAT_THRUSTS(7u),
    WEIGHTED_SQUAT_THRUSTS(8u),
    SQUAT_PLANK_PUSH_UP(9u),
    WEIGHTED_SQUAT_PLANK_PUSH_UP(10u),
    STANDING_T_ROTATION_BALANCE(11u),
    WEIGHTED_STANDING_T_ROTATION_BALANCE(12u),
    BARBELL_BURPEE(13u),
    BURPEE_BOX_JUMP_OVER_YES_LITERALLY_JUMPING_OVER_THE_BOX(15u),
    BURPEE_BOX_JUMP_STEP_UP_OVER(16u),
    LATERAL_BARBELL_BURPEE(17u),
    TOTAL_BODY_BURPEE_OVER_BAR(18u),
    BURPEE_BOX_JUMP_OVER(19u),
    BURPEE_WHEELCHAIR(20u),

    /** Returned for any raw value not present in the profile. */
    INVALID(UShort.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UShort, TotalBodyExerciseName> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UShort): TotalBodyExerciseName =
            byValue[value] ?: INVALID
    }
}
