/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.213.0Release
// Tag = production/release/21.213.0-0-g9e10ea9c
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * Named values for the FIT profile type `user_local_id`.
 *
 * This type is not modelled as an enum: it is a bit mask or a scalar with named
 * thresholds, so values outside the list below are meaningful.
 */
public object UserLocalIdValues {
    public const val LOCAL_MIN: UShort = 0x0000u
    public const val LOCAL_MAX: UShort = 0x000Fu
    public const val STATIONARY_MIN: UShort = 0x0010u
    public const val STATIONARY_MAX: UShort = 0x00FFu
    public const val PORTABLE_MIN: UShort = 0x0100u
    public const val PORTABLE_MAX: UShort = 0xFFFEu

    /** The FIT invalid sentinel for this type's base type. */
    public val INVALID: UShort = UShort.MAX_VALUE
}
