/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.213.0Release
// Tag = production/release/21.213.0-0-g9e10ea9c
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `weather_report`.
 */
public enum class WeatherReport(
    public val value: UByte,
) {
    CURRENT(0u),
    FORECAST(1u), // Deprecated use hourly_forecast instead
    DAILY_FORECAST(2u),

    /** Returned for any raw value not present in the profile. */
    INVALID(UByte.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UByte, WeatherReport> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UByte): WeatherReport =
            byValue[value] ?: INVALID
    }
}
