/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.215.0Release
// Tag = production/release/21.215.0-0-g907088c2
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `wkt_step_target`.
 */
public enum class WktStepTarget(
    public val value: UByte,
) {
    SPEED(0u),
    HEART_RATE(1u),
    OPEN(2u),
    CADENCE(3u),
    POWER(4u),
    GRADE(5u),
    RESISTANCE(6u),
    POWER_3S(7u),
    POWER_10S(8u),
    POWER_30S(9u),
    POWER_LAP(10u),
    SWIM_STROKE(11u),
    SPEED_LAP(12u),
    HEART_RATE_LAP(13u),

    /** Returned for any raw value not present in the profile. */
    INVALID(UByte.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UByte, WktStepTarget> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UByte): WktStepTarget =
            byValue[value] ?: INVALID
    }
}
