/////////////////////////////////////////////////////////////////////////////////////////////
// Copyright 2026 Garmin International, Inc.
// Licensed under the Flexible and Interoperable Data Transfer (FIT) Protocol License; you
// may not use this file except in compliance with the Flexible and Interoperable Data
// Transfer (FIT) Protocol License.
/////////////////////////////////////////////////////////////////////////////////////////////
// ****WARNING****  This file is auto-generated!  Do NOT edit this file.
// Profile Version = 21.217.0Release
// Tag = production/release/21.217.0-0-g248b1c46
/////////////////////////////////////////////////////////////////////////////////////////////

package com.garmin.fit.types

/**
 * FIT profile type `yds_grading_scale`.
 */
public enum class YdsGradingScale(
    public val value: UByte,
) {
    _5_1(0u), // 5.1
    _5_2(1u), // 5.2
    _5_3(2u), // 5.3
    _5_4(3u), // 5.4
    _5_5(4u), // 5.5
    _5_6(5u), // 5.6
    _5_7(6u), // 5.7
    _5_8(7u), // 5.8
    _5_9(8u), // 5.9
    _5_10(9u), // 5.1
    _5_10A(10u), // 5.10a
    _5_10B(11u), // 5.10b
    _5_10C(12u), // 5.10c
    _5_10D(13u), // 5.10d
    _5_11(14u), // 5.11
    _5_11A(15u), // 5.11a
    _5_11B(16u), // 5.11b
    _5_11C(17u), // 5.11c
    _5_11D(18u), // 5.11d
    _5_12(19u), // 5.12
    _5_12A(20u), // 5.12a
    _5_12B(21u), // 5.12b
    _5_12C(22u), // 5.12c
    _5_12D(23u), // 5.12d
    _5_13(24u), // 5.13
    _5_13A(25u), // 5.13a
    _5_13B(26u), // 5.13b
    _5_13C(27u), // 5.13c
    _5_13D(28u), // 5.13d
    _5_14(29u), // 5.14
    _5_14A(30u), // 5.14a
    _5_14B(31u), // 5.14b
    _5_14C(32u), // 5.14c
    _5_14D(33u), // 5.14d
    _5_15(34u), // 5.15
    _5_15A(35u), // 5.15a
    _5_15B(36u), // 5.15b
    _5_15C(37u), // 5.15c
    _5_15D(38u), // 5.15d
    _5_1_MINUS(39u), // 5.1-
    _5_1_PLUS(40u), // 5.1+
    _5_2_MINUS(41u), // 5.2-
    _5_2_PLUS(42u), // 5.2+
    _5_3_MINUS(43u), // 5.3-
    _5_3_PLUS(44u), // 5.3+
    _5_4_MINUS(45u), // 5.4-
    _5_4_PLUS(46u), // 5.4+
    _5_5_MINUS(47u), // 5.5-
    _5_5_PLUS(48u), // 5.5+
    _5_6_MINUS(49u), // 5.6-
    _5_6_PLUS(50u), // 5.6+
    _5_7_MINUS(51u), // 5.7-
    _5_7_PLUS(52u), // 5.7+
    _5_8_MINUS(53u), // 5.8-
    _5_8_PLUS(54u), // 5.8+
    _5_9_MINUS(55u), // 5.9-
    _5_9_PLUS(56u), // 5.9+
    _5_10_MINUS(57u), // 5.10-
    _5_10_PLUS(58u), // 5.10+
    _5_11_MINUS(59u), // 5.11-
    _5_11_PLUS(60u), // 5.11+
    _5_12_MINUS(61u), // 5.12-
    _5_12_PLUS(62u), // 5.12+
    _5_13_MINUS(63u), // 5.13-
    _5_13_PLUS(64u), // 5.13+
    _5_14_MINUS(65u), // 5.14-
    _5_14_PLUS(66u), // 5.14+
    _5_15_MINUS(67u), // 5.15-
    _5_15_PLUS(68u), // 5.15+

    /** Returned for any raw value not present in the profile. */
    INVALID(UByte.MAX_VALUE),
    ;

    public companion object {
        private val byValue: Map<UByte, YdsGradingScale> =
            entries.associateBy { it.value }

        /** Maps a raw FIT value onto its enum entry, falling back to [INVALID]. */
        public fun fromValue(value: UByte): YdsGradingScale =
            byValue[value] ?: INVALID
    }
}
